version: "2.0"
services:
    cloudera:
        image: cloudera/quickstart
        ports:
            - 7180:7180
            - 80:80
            - 7187:7187
            - 8888:8888
            - 8088:8088
            - 8040:8040
        command: /usr/bin/docker-quickstart
        privileged: true
        stdin_open: true
        tty: true
        hostname: "quickstart.cloudera"
        extra_hosts:
            - "quickstart.cloudera:127.0.0.1"
        volumes:
            - ./labs:/root/labs
