version: "2.0"
services:
    cloudera:
        image: cloudera/quickstart
        ports:
            - 80:80
        command: /usr/bin/docker-quickstart
        privileged: true
        stdin_open: true
        tty: true
        hostname: "quickstart.cloudera"
        extra_hosts:
            - "quickstart.cloudera:127.0.0.1"
        volumes:
            - ./labs:/root/labs
