version: "2.0"
services:
    cloudera:
        build: './cloudera'
        ports:
            - 80:80
            - 7180:7180
            - 7187:7187
            - 8088:8088
            - 8888:8888
            - 9092:9092
            - 9090:9090
            - 9083:9083
        command: /usr/bin/docker-quickstart & /bin/bash -l
        stdin_open: true
        tty: true
        privileged: true
        hostname: "quickstart.cloudera"
        extra_hosts:
            - "quickstart.cloudera:127.0.0.1"
        volumes:
            - ./labs:/root/labs
            - ./ext:/ext
            - ./proj:/root/proj
        env_file:
            - env.env
