version: "2.0"
services:
    cloudera:
        image: cloudera/quickstart
        ports:
            - 80:80
            - 7180:7180
            - 7187:7187
            - 8088:8088
            - 8888:8888
        command: /bin/bash /ext/start.sh
        privileged: true
        stdin_open: true
        tty: true
        hostname: "quickstart.cloudera"
        extra_hosts:
            - "quickstart.cloudera:127.0.0.1"
        volumes:
            - ./labs:/root/labs
            - ./ext:/ext
        env_file:
            - env.env
